[DEBUG][Qt] 05.08.2025 12:41:55 [] (unknown:0) - Session start time .......: 20250805_124155
[DEBUG][Qt] 05.08.2025 12:41:55 [] (unknown:0) - Slicer version ...........: 5.8.1 (revision 33241 / 11eaf62) win-amd64 - installed release
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Operating system .........: Windows /  Personal / (Build 26100, Code Page 65001) - 64-bit
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Memory ...................: 32439 MB physical, 34871 MB virtual
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - CPU ......................: GenuineIntel , 20 cores, 20 logical processors
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - VTK configuration ........: OpenGL2 rendering, TBB threading
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Qt configuration .........: version 5.15.2, with SSL, requested OpenGL 3.2 (compatibility profile)
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - DCMTK configuration ......: version 3.6.8, no SSL
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Internationalization .....: disabled, language=
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Developer mode ...........: enabled
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Application path .........: C:/Users/chris/AppData/Local/slicer.org/Slicer 5.8.1/bin
[DEBUG][Qt] 05.08.2025 12:41:56 [] (unknown:0) - Additional module paths ..: slicer.org/Extensions-33241/SegmentEditorExtraEffects/lib/Slicer-5.8/qt-loadable-modules, slicer.org/Extensions-33241/SegmentEditorExtraEffects/lib/Slicer-5.8/qt-scripted-modules, slicer.org/Extensions-33241/SlicerVMTK/lib/Slicer-5.8/qt-loadable-modules, slicer.org/Extensions-33241/SlicerVMTK/lib/Slicer-5.8/qt-scripted-modules, slicer.org/Extensions-33241/ExtraMarkups/lib/Slicer-5.8/qt-loadable-modules, slicer.org/Extensions-33241/MarkupsToModel/lib/Slicer-5.8/qt-loadable-modules, slicer.org/Extensions-33241/Sandbox/lib/Slicer-5.8/qt-loadable-modules, slicer.org/Extensions-33241/Sandbox/lib/Slicer-5.8/qt-scripted-modules, C:/Users/chris/Documents/repos/DAI-Vera/slicer_scripts/DAI_Workflow\workflow
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) -   Error(s):
    CLI executable: C:/Users/chris/AppData/Local/slicer.org/Slicer 5.8.1/slicer.org/Extensions-33241/SlicerVMTK/lib/Slicer-5.8/qt-loadable-modules/vtkvmtk.py
    The process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) - Fail to instantiate module  "vtkvmtk"
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "<string>", line 1, in <module>
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Python\Lib\imp.py", line 169, in load_source
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -     module = _exec(spec, sys.modules[name])
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "<frozen importlib._bootstrap>", line 613, in _exec
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "<frozen importlib._bootstrap_external>", line 846, in exec_module
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "<frozen importlib._bootstrap_external>", line 983, in get_code
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -   File "C:/Users/chris/Documents/repos/DAI-Vera/slicer_scripts/DAI_Workflow/workflow/workflow.py", line 306
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -     return segmentation_node
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) -     ^
[CRITICAL][Stream] 05.08.2025 12:41:59 [] (unknown:0) - SyntaxError: invalid syntax
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) - loadSourceAsModule - Failed to load file "C:/Users/chris/Documents/repos/DAI-Vera/slicer_scripts/DAI_Workflow/workflow/workflow.py"  as module "workflow" !
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) - Fail to instantiate module  "workflow"
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) - The following modules failed to be instantiated:
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) -    vtkvmtk
[CRITICAL][Qt] 05.08.2025 12:41:59 [] (unknown:0) -    workflow
[DEBUG][Python] 05.08.2025 12:42:00 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Slicer-5.8\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:40) - Scripted subject hierarchy plugin registered: SegmentEditor
[DEBUG][Python] 05.08.2025 12:42:00 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Slicer-5.8\qt-scripted-modules\SubjectHierarchyPlugins\AbstractScriptedSubjectHierarchyPlugin.py:40) - Scripted subject hierarchy plugin registered: SegmentStatistics
[DEBUG][Qt] 05.08.2025 12:42:00 [] (unknown:0) - Switch to module:  "Welcome"
[INFO][Stream] 05.08.2025 12:42:01 [] (unknown:0) - Loading Slicer RC file [C:/Users/chris/.slicerrc.py]
[DEBUG][Qt] 05.08.2025 12:42:03 [] (unknown:0) - Switch to module:  "DICOM"
[INFO][Python] 05.08.2025 12:42:08 [Python] (C:/Users/chris/AppData/Local/slicer.org/Slicer 5.8.1/bin/../lib/Slicer-5.8/qt-scripted-modules/DICOMScalarVolumePlugin.py:445) - Loading with imageIOName: GDCM
[DEBUG][Python] 05.08.2025 12:43:55 [Python] (C:/Users/chris/AppData/Local/slicer.org/Slicer 5.8.1/bin/../lib/Slicer-5.8/qt-scripted-modules/DICOMScalarVolumePlugin.py:557) - DICOM window/level (40.0/400.0) set to volume '18: CorCTALow  0.6  B10f 65%' from SOP instance 1.3.12.2.1107.5.1.4.54023.30000004093016410718700008219.
[DEBUG][Python] 05.08.2025 12:43:55 [Python] (C:/Users/chris/AppData/Local/slicer.org/Slicer 5.8.1/bin/../lib/Slicer-5.8/qt-scripted-modules/DICOMScalarVolumePlugin.py:557) - DICOM window/level (-600.0/1200.0) set to volume '18: CorCTALow  0.6  B10f 65%' from SOP instance 1.3.12.2.1107.5.1.4.54023.30000004093016410718700008219.
[DEBUG][Qt] 05.08.2025 12:45:07 [] (unknown:0) - Switch to module:  "ExtensionWizard"
[DEBUG][Python] 05.08.2025 12:45:34 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Python\Lib\site-packages\git\cmd.py:1253) - Popen(['git', 'version'], cwd=C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1, stdin=None, shell=False, universal_newlines=False)
[DEBUG][Python] 05.08.2025 12:45:34 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Python\Lib\site-packages\git\cmd.py:1253) - Popen(['git', 'version'], cwd=C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1, stdin=None, shell=False, universal_newlines=False)
[DEBUG][Python] 05.08.2025 12:45:34 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\bin\Python\SlicerWizard\Utilities.py:426) - 'C:/Users/chris/Documents/repos/SlicerWorkflowExt/DAI_Workflow' is not a git repository
[DEBUG][Python] 05.08.2025 12:45:34 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Python\Lib\site-packages\charset_normalizer\api.py:439) - Encoding detection: ascii is most likely the one.
[DEBUG][Python] 05.08.2025 12:45:34 [Python] (C:\Users\chris\AppData\Local\slicer.org\Slicer 5.8.1\lib\Python\Lib\site-packages\charset_normalizer\api.py:439) - Encoding detection: ascii is most likely the one.
[DEBUG][Qt] 05.08.2025 12:46:53 [] (unknown:0) - Switch to module:  ""
